# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psc < Formula
  desc "lightweight postgres monitor for the terminal"
  homepage ""
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.3.0/psc_Darwin_x86_64.tar.gz"
      sha256 "c2ef517527ae1b3bb4102a34ff051f437d17944461a49aeb2d0133c7ba3873dc"

      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.3.0/psc_Darwin_arm64.tar.gz"
      sha256 "5c632bc19940e7213ee34738c5d40b76ea310c84a702c1e2272a1500c9ed8dc9"

      def install
        bin.install "psc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.3.0/psc_Linux_x86_64.tar.gz"
      sha256 "026bb4e95eb345c25d1448e223c87b9a8eb737a090be9e37058a719634923ad1"
      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.3.0/psc_Linux_arm64.tar.gz"
      sha256 "994ab8068df738c8a3c31108b52bf8e14dcd3486bdb2048bb6dd5e0d0df5e564"
      def install
        bin.install "psc"
      end
    end
  end

  test do
    system "#{bin}/psc --version"
  end
end
