# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psc < Formula
  desc "TUI-based daemon for running large-scale PostgreSQL data fix migrations"
  homepage ""
  version "2.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.1/psc_Darwin_x86_64.tar.gz"
      sha256 "4d9921fc2f73a0f3c36bd8fd4560b18326f093eb6a303358e3d5f5b60044bc06"

      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.1/psc_Darwin_arm64.tar.gz"
      sha256 "6bce5abd96ab5e49c03c5da0e93155030f6e90fe52c24c4e065e3c49f518d017"

      def install
        bin.install "psc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.1/psc_Linux_x86_64.tar.gz"
      sha256 "200acc4efb9501b64ad345852a58cd17f11b9044ec5f3f5cf4841beaddf70c1d"
      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.1/psc_Linux_arm64.tar.gz"
      sha256 "4f03d542f3829855c3be0580b10e77b4b18d8ddd868824ef695b7ead1b7cb715"
      def install
        bin.install "psc"
      end
    end
  end

  test do
    system "#{bin}/psc --version"
  end
end
