# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psc < Formula
  desc "lightweight postgres monitor for the terminal"
  homepage ""
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.0.0/psc_Darwin_x86_64.tar.gz"
      sha256 "9977496b1d7527ab47ac804b082e66e1b09283daafe395cc85a3ef3279cbb264"

      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.0.0/psc_Darwin_arm64.tar.gz"
      sha256 "12de16d86346dc39454bb3eb47ef5190aa2dd36d6e2a4204c6a69927f43e480a"

      def install
        bin.install "psc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.0.0/psc_Linux_x86_64.tar.gz"
      sha256 "7ed0cdcf28011ae57e37ed54add6d62409b717e0d684ec87ea63f36f9a03cddd"
      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v1.0.0/psc_Linux_arm64.tar.gz"
      sha256 "2cadff9c03b9103c0b7f5272f1d27ec78d4e1d360868098147ab80a70b67f97d"
      def install
        bin.install "psc"
      end
    end
  end

  test do
    system "#{bin}/psc --version"
  end
end
